export const cardStyles = {
    container: {
        position: 'relative',
        backgroundColor: '#1a1a1a',
        borderRadius: '15px',
        color: 'white',
        boxShadow: '0 4px 8px rgba(0,0,0,0.5)',
        padding: '15px',
        overflow: 'hidden',
        display: 'grid',
        gridTemplateRows: 'auto auto 1fr 1fr',
        gap: '5px',
        height: '100%',
        width: '100%',
        boxSizing: 'border-box',
    },
    header: {
        borderBottom: '2px solid #333',
        paddingBottom: '10px',
    },
    title: {
        fontSize: '1.2rem',
        fontWeight: 'bold',
        marginBottom: '5px',
    },
    subtitle: {
        fontSize: '1rem',
        color: '#888',
    },
    propertyGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(4, 1fr)',
        gap: '8px',
        padding: '8px 12px',
        backgroundColor: '#252525',
        borderRadius: '8px',
        fontSize: '0.9rem',
        alignSelf: 'stretch',
        minHeight: 'fit-content',
    },
    property: {
        display: 'flex',
        flexDirection: 'column',
        gap: '2px',
        alignItems: 'center',
        textAlign: 'center',
    },
    propertyLabel: {
        fontSize: '0.75rem',
        color: '#888',
        textTransform: 'capitalize',
    },
    propertyValue: {
        fontSize: '0.85rem',
        color: '#fff',
        fontWeight: '500',
    },
    wording: {
        padding: '12px',
        backgroundColor: '#252525',
        borderRadius: '8px',
        fontSize: '0.8rem', 
        overflow: 'auto',
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
        scrollbarColor: "#333 #1a1a1a",
        "&::-webkit-scrollbar": {
            width: "8px",
            height: "8px",
        },
        "&::-webkit-scrollbar-track": {
            background: "#1a1a1a",
            borderRadius: "4px",
            marginBottom: "0",
        },
        "&::-webkit-scrollbar-thumb": {
            background: "#333",
            borderRadius: "4px",
            "&:hover": {
                background: "#444",
            },
        },
    },
};