export const handStyles = {
    container: {
      backgroundColor: "#1a1a1a",
      display: "flex",
      flexGrow: 0,
      flexShrink: 1,
      flexBasis: "96vw",
      justifyContent: "center",
      alignItems: "center",
      position: "absolute",
      bottom: 10,
      width: "100%",
      height: "30%",
      borderRadius: "15px",
      boxShadow: "0 4px 8px rgba(0,0,0,0.5)",
    },
    dropArea: {
      position: "absolute",
      top: 0,
      left: 0,
      width: "100%",
      height: "100%",
      backgroundColor: "rgba(255, 255, 255, 0.1)",
      display: "none",
      zIndex: 1,
      borderRadius: "15px",
      transition: "background-color 0.2s ease",
    },
    dropAreaActive: {
      display: "block",
      backgroundColor: "rgba(255, 255, 255, 0.2)",
    },
    select: {
      position: "absolute",
      top: "10px",
      left: "20px",
      backgroundColor: "#252525",
      color: "white",
      border: "1px solid #333",
      borderRadius: "4px",
      padding: "6px",
      fontSize: "12px",
      cursor: "pointer",
      "&:hover": {
        backgroundColor: "#333",
      },
    },
    cardsContainer: {
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      padding: "0 20px",
      overflowX: "auto",      // Allow horizontal scrolling if needed
      overflowY: "hidden",    // Prevent vertical scrolling
    },
};