export const tableStyles = {
    table: {
      width: "100%",
      borderCollapse: "collapse",
      color: "white",
      backgroundColor: "#1a1a1a",
    },
    tableHeader: {
      position: "sticky",
      top: 0,
      backgroundColor: "#252525",
      zIndex: 1,
    },
    headerCell: {
      padding: "8px",
      borderBottom: "2px solid #333",
      fontSize: "13px",
    },
    headerButton: {
      background: "none",
      border: "none",
      color: "#888",
      fontSize: "13px",
      fontWeight: "bold",
      cursor: "pointer",
      padding: "4px",
      width: "100%",
      textAlign: "center",
      color: "white",
    },
    row: {
      transition: "background-color 0.2s ease",
      cursor: "pointer",
      "&:hover": {
        backgroundColor: "#252525",
      },
    },
    cell: {
      padding: "6px 8px",
      borderBottom: "1px solid #333",
      fontSize: "12px",
    },
    container: {
      backgroundColor: "#1a1a1a",
      borderRadius: "15px",
      boxShadow: "0 4px 8px rgba(0,0,0,0.5)",
      overflow: "hidden",
    },
    filters: {
      padding: "15px",
      backgroundColor: "#252525",
      borderBottom: "1px solid #333",
    },
    select: {
      backgroundColor: "#1a1a1a",
      color: "white",
      border: "1px solid #333",
      borderRadius: "4px",
      padding: "6px",
      margin: "4px",
      cursor: "pointer",
      fontSize: "12px",
    },
    searchInput: {
      backgroundColor: "#1a1a1a",
      color: "white",
      border: "1px solid #333",
      borderRadius: "4px",
      padding: "6px",
      width: "100%",
      marginBottom: "8px",
      fontSize: "12px",
    },
    button: {
      backgroundColor: "#333",
      color: "white",
      border: "none",
      borderRadius: "4px",
      padding: "6px 10px",
      cursor: "pointer",
      transition: "background-color 0.2s ease",
      fontSize: "12px",
      "&:hover": {
        backgroundColor: "#444",
      },
    },
  };